try {
  console.log("Trying...");
  console.log(a);
} catch (error) {
  console.log("Caught error:");
} 

console.log("you are in the end of the program!!!");
